
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\x13\x8a1\x93}\xdc?\xeb\xb1\x95\xd3\x0f\x88r2\x8c'
    
_lr_action_items = {'STAR':([3,5,8,10,11,],[-5,8,-6,-7,8,]),'SINGLE':([0,3,4,5,8,9,10,11,],[3,-5,3,3,-6,3,-7,-1,]),'LPAREN':([0,3,4,5,8,9,10,11,],[4,-5,4,4,-6,4,-7,-1,]),'RPAREN':([1,3,4,5,6,7,8,10,11,],[-2,-5,-4,-4,10,-3,-6,-7,-1,]),'OR':([3,5,8,10,11,],[-5,9,-6,-7,9,]),'$end':([0,1,2,3,5,7,8,10,11,],[-4,-2,0,-5,-4,-3,-6,-7,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'elts':([0,4,5,],[1,1,7,]),'RE':([0,4,],[2,6,]),'elt':([0,4,5,9,],[5,5,5,11,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> RE","S'",1,None,None,None),
  ('elt -> elt OR elt','elt',3,'p_elt_or','/Users/HTX/Documents/\xe4\xbd\x9c\xe4\xb8\x9a/\xe8\xae\xa1\xe7\xae\x97\xe6\x9c\xba/Udacity/RE interpreter.py',54),
  ('RE -> elts','RE',1,'p_RE_elts','/Users/HTX/Documents/\xe4\xbd\x9c\xe4\xb8\x9a/\xe8\xae\xa1\xe7\xae\x97\xe6\x9c\xba/Udacity/RE interpreter.py',58),
  ('elts -> elt elts','elts',2,'p_elts','/Users/HTX/Documents/\xe4\xbd\x9c\xe4\xb8\x9a/\xe8\xae\xa1\xe7\xae\x97\xe6\x9c\xba/Udacity/RE interpreter.py',62),
  ('elts -> <empty>','elts',0,'p_elts_empty','/Users/HTX/Documents/\xe4\xbd\x9c\xe4\xb8\x9a/\xe8\xae\xa1\xe7\xae\x97\xe6\x9c\xba/Udacity/RE interpreter.py',66),
  ('elt -> SINGLE','elt',1,'p_elt_single','/Users/HTX/Documents/\xe4\xbd\x9c\xe4\xb8\x9a/\xe8\xae\xa1\xe7\xae\x97\xe6\x9c\xba/Udacity/RE interpreter.py',70),
  ('elt -> elt STAR','elt',2,'p_elt_star','/Users/HTX/Documents/\xe4\xbd\x9c\xe4\xb8\x9a/\xe8\xae\xa1\xe7\xae\x97\xe6\x9c\xba/Udacity/RE interpreter.py',74),
  ('elt -> LPAREN RE RPAREN','elt',3,'p_elt_paren','/Users/HTX/Documents/\xe4\xbd\x9c\xe4\xb8\x9a/\xe8\xae\xa1\xe7\xae\x97\xe6\x9c\xba/Udacity/RE interpreter.py',78),
]
